language: python
python:
  - "3.7"
install:
  - pip install pytest
  - pip install pylint
  - attrs==20.3.0
  - beautifulsoup4==4.8.2
  - boto3==1.16.39
  - botocore==1.19.39
  - brotli==1.0.9
  - cffi==1.14.4
  - chardet==3.0.4
  - click==7.1.2
  - cryptography==3.0
  - dash==1.17.0
  - dash-bootstrap-components==0.10.7
  - dash-core-components==1.13.0
  - dash-html-components==1.1.1
  - dash-ly==0.17.3
  - dash-renderer==1.8.3
  - dash-table==4.11.0
  - flask==1.1.2
  - flask-compress==1.8.0
  - flask-seasurf==0.2.2
  - flask-talisman==0.7.0
  - future==0.18.2
  - idna==2.8
  - iniconfig==1.1.1
  - itsdangerous==1.1.0
  - jinja2==2.11.2
  - jmespath==0.10.0
  - jwt==1.1.0
  - lxml==4.5.0
  - markupsafe==1.1.1
  - more-itertools==8.6.0
  - mysql-connector-python==8.0.22
  - packaging==20.5
  - percy==2.0.2
  - plotly==4.12.0
  - pluggy==0.13.1
  - protobuf==3.14.0
  - py==1.9.0
  - pycparser==2.20
  - pymysql==0.10.1
  - pyopenssl==19.1.0
  - pyparsing==2.4.7
  - pytest==6.0.1
  - pytest-mock==3.2.0
  - pytest-sugar==0.9.4
  - requests==2.21.0
  - retrying==1.3.3
  - s3transfer==0.3.3
  - selenium==3.141.0
  - soupsieve==2.0.1
  - sqlalchemy==1.3.20
  - termcolor==1.1.0
  - toml==0.10.2
  - urllib3==1.26.2
  - waitress==1.4.3
  - werkzeug==1.0.1
# command to run tests
script:
  - python -m pytest tests/
  - pylint **/*.py --disable=E1101