language: python
python:
  - "3.7"
install:
  - pip install pytest
  - pip install pylint
  - pip install -r req.txt
# command to run tests
script:
  - python -m pytest tests/
  - pylint **/*.py --disable=C0103